# Generated by Django 5.0.3 on 2026-09-07 08:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('file_type', models.CharField(choices=[('LEDGER', 'Ledger'), ('STATEMENT', 'Statement')], max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LedgerRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(help_text='Original identifier (trade_id or reference)', max_length=100)),
                ('instrument', models.CharField(help_text='Normalized symbol/instrument', max_length=50)),
                ('side', models.CharField(help_text='Normalized side (BUY or SELL)', max_length=10)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('amount', models.DecimalField(decimal_places=8, help_text='Total/Gross amount', max_digits=20)),
                ('executed_at', models.DateTimeField()),
                ('status', models.CharField(help_text='Original status', max_length=20)),
                ('source_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reconciliation.datafile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReconciliationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('ledger_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_runs', to='reconciliation.datafile')),
                ('statement_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statement_runs', to='reconciliation.datafile')),
            ],
        ),
        migrations.CreateModel(
            name='StatementRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(help_text='Original identifier (trade_id or reference)', max_length=100)),
                ('instrument', models.CharField(help_text='Normalized symbol/instrument', max_length=50)),
                ('side', models.CharField(help_text='Normalized side (BUY or SELL)', max_length=10)),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=20)),
                ('price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('amount', models.DecimalField(decimal_places=8, help_text='Total/Gross amount', max_digits=20)),
                ('executed_at', models.DateTimeField()),
                ('status', models.CharField(help_text='Original status', max_length=20)),
                ('source_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reconciliation.datafile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MatchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_type', models.CharField(choices=[('EXACT', 'Exact Match'), ('FUZZY', 'Fuzzy Match (Drift)'), ('UNMATCHED_LEDGER', 'Unmatched (Ledger Only)'), ('UNMATCHED_STATEMENT', 'Unmatched (Statement Only)'), ('MANUAL', 'Manually Matched'), ('IGNORED', 'Ignored (Cancelled)')], max_length=25)),
                ('amount_discrepancy', models.DecimalField(decimal_places=8, default=0, max_digits=20)),
                ('time_discrepancy_seconds', models.IntegerField(default=0)),
                ('resolved_by_human', models.BooleanField(default=False)),
                ('ledger_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reconciliation.ledgerrecord')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='reconciliation.reconciliationrun')),
                ('statement_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reconciliation.statementrecord')),
            ],
        ),
    ]
