# Generated by Django 5.0.3 on 2026-09-07 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reconciliationrun',
            name='ledger_file',
        ),
        migrations.RemoveField(
            model_name='reconciliationrun',
            name='statement_file',
        ),
    ]
